In [65]:
import pandas as pd
from sklearn import model_selection
from sklearn import neighbors
from sklearn import linear_model
from sklearn import svm
from sklearn import tree
from sklearn import neural_network

In [66]:
data = pd.read_csv(r"C:\Users\a\OneDrive\Desktop\Project\DATA\csv_files\tic-tac-toe-endgame.csv")
data

    V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0    x  x  x  x  o  o  x  o  o  positive
1    x  x  x  x  o  o  o  x  o  positive
2    x  x  x  x  o  o  o  o  x  positive
3    x  x  x  x  o  o  o  b  b  positive
4    x  x  x  x  o  o  b  o  b  positive
..  .. .. .. .. .. .. .. .. ..       ...
953  o  x  x  x  o  o  o  x  x  negative
954  o  x  o  x  x  o  x  o  x  negative
955  o  x  o  x  o  x  x  o  x  negative
956  o  x  o  o  x  x  x  o  x  negative
957  o  o  x  x  x  o  o  x  x  negative

[958 rows x 10 columns]

In [67]:
data.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
dtype: int64

In [68]:
data = data.rename(columns = {"V10":"target"})
data

    V1 V2 V3 V4 V5 V6 V7 V8 V9    target
0    x  x  x  x  o  o  x  o  o  positive
1    x  x  x  x  o  o  o  x  o  positive
2    x  x  x  x  o  o  o  o  x  positive
3    x  x  x  x  o  o  o  b  b  positive
4    x  x  x  x  o  o  b  o  b  positive
..  .. .. .. .. .. .. .. .. ..       ...
953  o  x  x  x  o  o  o  x  x  negative
954  o  x  o  x  x  o  x  o  x  negative
955  o  x  o  x  o  x  x  o  x  negative
956  o  x  o  o  x  x  x  o  x  negative
957  o  o  x  x  x  o  o  x  x  negative

[958 rows x 10 columns]

In [69]:
def encoding(df, columns):
    df = df.copy()
    for column in columns:
        dummies = pd.get_dummies(data[column], prefix = column)
        df = pd.concat([df,dummies], axis = 1)
        df = df.drop(column, axis = 1)
    return df

In [70]:
encoding(data, ["V" + str(x) for x in range(1,10)])

,target,V1_b,V1_o,V1_x,V2_b,V2_o,V2_x,V3_b,V3_o,V3_x,...,V6_x,V7_b,V7_o,V7_x,V8_b,V8_o,V8_x,V9_b,V9_o,V9_x
0,positive,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
1,positive,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
2,positive,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
3,positive,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
4,positive,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,negative,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
954,negative,0,1,0,0,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,1
955,negative,0,1,0,0,0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
956,negative,0,1,0,0,0,1,0,1,0,...,1,0,0,1,0,1,0,0,0,1
957,negative,0,1,0,0,1,0,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [71]:
def preprocess(df):
    df = df.copy()

    df["target"] = df["target"].replace({"positive":1, "negative":0})

    df = encoding(
        df,
        columns = ["V" + str(x) for x in range(1,10)]
    )

    y = df["target"].copy()
    x = df.drop("target", axis = 1).copy()

    x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y, test_size = 0.3, random_state = 123)

    return x_train, x_test, y_train, y_test

In [72]:
x_train, x_test, y_train, y_test =  preprocess(data)

In [73]:
models = {
    "    K-Nearest Neighbor":neighbors.KNeighborsClassifier(),
    "   Logistic Regression":linear_model.LogisticRegression(),
    "Support Vector Machine":svm.SVC(),
    "         Decision Tree":tree.DecisionTreeClassifier(),
    "        Neural Network":neural_network.MLPClassifier()
}

for name, model in models.items():
    model.fit(x_train,y_train)
    print(f"{name} trained")

    K-Nearest Neighbor trained
   Logistic Regression trained
Support Vector Machine trained
         Decision Tree trained
        Neural Network trained

c:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [80]:
for name, model in models.items():
    score = model.score(x_test,y_test)
    print(f"{name}: Accuracy = {score}")

    K-Nearest Neighbor: Accuracy = 0.9236111111111112
   Logistic Regression: Accuracy = 0.9826388888888888
Support Vector Machine: Accuracy = 0.9756944444444444
         Decision Tree: Accuracy = 0.9548611111111112
        Neural Network: Accuracy = 0.9930555555555556